# Generated by Django 4.0.2 on 2022-08-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='department_id',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
