# Generated by Django 4.0.2 on 2022-08-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='XYZ', max_length=100)),
                ('created_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('descriptions', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='question_answer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('isOption', models.BooleanField()),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.custom_feedback')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question_answer_type')),
            ],
        ),
        migrations.CreateModel(
            name='optionsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
            ],
        ),
        migrations.CreateModel(
            name='general_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question_answer_type')),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.custom_feedback')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users_table')),
            ],
        ),
    ]
