# Generated by Django 4.0.2 on 2022-08-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_feedback',
            old_name='descriptions',
            new_name='description',
        ),
    ]
