# Generated by Django 4.0.2 on 2022-08-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('feedback', '0002_rename_descriptions_custom_feedback_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='votingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='XYZ', max_length=100)),
                ('created_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
