# Generated by Django 4.0.2 on 2022-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_votingfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_feedback',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votingfeedback',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
